version: '3.8'
services:
  chatGLM:
    image: paidax/chatglm2-6b-0.1
    container_name: chatglm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 8000:8000
    volumes:
      - chatglm-6b:/etc/model/chatglm-6b
    command: tail -f /dev/null

